CREATE USER jogador WITH PASSWORD 'senha';
GRANT CONNECT ON DATABASE dofus TO jogador;
GRANT USAGE ON SCHEMA public TO jogador;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jogador;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jogador;
